package io.finarkein.flux.fiber.hiu.model;

/**
 * This class stores the callback response for your consent request init.
 */
public class ConsentToken {

    /**
     * This variable stores the request id generated during consent init.
     */
    private String requestId;

    /**
     * This variable stores the consent request id generated by the gateway.
     */
    private String consentRequestId;

    /**
     * This variable stores the error if received.
     */
    private Error error;

    /**
     * Constructs a token with given request identifier.
     *
     * @param requestId A string containing requestId.
     */
    public ConsentToken(String requestId) {
        this.requestId = requestId;
    }

    /**
     * @return a string representing consentRequestId.
     */
    public String getConsentRequestId() {
        return consentRequestId;
    }

    /**
     * @param consentRequestId A string containing consentRequestId.
     */
    public void setConsentRequestId(String consentRequestId) {
        this.consentRequestId = consentRequestId;
    }

    /**
     * @return A string representing requestId.
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * @return A Error representing error.
     */
    public Error getError() {
        return error;
    }
}
