package io.finarkein.flux.fiber.hiu.model;

import lombok.Data;
import lombok.Setter;

/**
 * A class representing the data request information.
 */
@Data
public class DataFetchId {

    /**
     * This variable stores the request Id generated during the data request.
     */
    private String fetchId;

    /**
     * This variable stores the transaction Id generated by the consent manager.
     */
    @Setter
    private String transactionId;

    /**
     * A no parameter constructor.
     */
    public DataFetchId() {
        // default for Jackson
    }

    /**
     * Class constructor specifying fetchId.
     *
     * @param fetchId A string containing fetch Id.
     */
    public DataFetchId(String fetchId) {
        this.fetchId = fetchId;
    }


}
