# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created

name: Maven Package

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          server-id: github

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -DskipTests -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/finarkein/flux-sdk -Pgithub-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
